### ISSUE TITLE
Render message event types

### ISSUE THREAD

**Issue by turt2live** [turt2live/evelium#24]
* [x] m.image - https://github.com/turt2live/evelium/issues/25
* [x] m.emote - https://github.com/turt2live/evelium/issues/27
* [x] m.text
* [x] m.notice
* [ ] m.video - https://github.com/turt2live/evelium/issues/26
* [ ] m.audio - https://github.com/turt2live/evelium/issues/68
* [ ] m.file - https://github.com/turt2live/evelium/issues/79
* [ ] m.location - https://github.com/turt2live/evelium/issues/80
