### ISSUE TITLE
Send attachments

### ISSUE THREAD

**Issue by turt2live** [turt2live/evelium#69]
* [ ] By clicking a button
* [ ] By dropping them on the page
* [ ] By pasting from your clipboard into the composer

The implementation should also be aware of the different media event types and send the most appropriate one (eg: `image/*` mimetypes get sent as `m.image` events).

Viewing these events is handled by #24
