### ISSUE TITLE
General app performance

### ISSUE THREAD

**Issue by turt2live** [turt2live/evelium#75]
* [ ] Account data can be slow to load on startup
* [ ] Rooms pop in during the initial /sync slowly
* [ ] Scrolling the room list can be sluggish (#63)
