### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by turt2live** [turt2live/evelium#84]
* [ ] `/join` - https://github.com/turt2live/evelium/issues/22
* [ ] `/leave` and `/part` - https://github.com/turt2live/evelium/issues/23
* [ ] `/me` - https://github.com/turt2live/evelium/issues/28
* [ ] `/invite` - https://github.com/turt2live/evelium/issues/81
* [ ] `/kick` - https://github.com/turt2live/evelium/issues/82
* [ ] `/ban` - https://github.com/turt2live/evelium/issues/83
